export const DEFAULT_GENERAL_SETTINGS = {
  bookingMaxDaysAhead: 30,
  splitRideMinBookingHours: 24,
  splitRideRefundRestrictionHours: 24,
  privateRideMinBookingHours: 1,
  privateRideRefundRestrictionHours: 1,
  matchingNoDriverNotifyHours: 48,
  matchingLastNotifyHours: 1,
  cancellationFreeWindowHours: 24,
  cancellationPercentage50Hours: 3,
  waitingReminderIntervals: 10,
  waitingTimeMinutes: 60,

  dayFareInitialCharge: 3.8,
  dayFarePerKMRate: 0.95,
  dayFareWaitingCharge: 17,
  nightFareInitialCharge: 4.8,
  nightFarePerKMRate: 1.1,
  nightFareWaitingCharge: 19,
  holidayIncreasePercentage: 20,
  perLuggageCharge: 2,
  fivePassengerExtraChargePercentage: 20,
  sixPassengerExtraChargePercentage: 40,
  baseFare: 20,
  splitRideMatchedSurchargePercent: 30,
  platformVat: 9,
  platformCommissionPercent: 10,
  driverPlatformFeePercent: 15,
  driverVatPercent: 19,

  supportContract: '+357XXXXXXXX',
  supportEmail: 'support@yourapp.com',
} as const;

export const GENERAL_KEYS = [
  'bookingMaxDaysAhead',
  'splitRideMinBookingHours',
  'splitRideRefundRestrictionHours',
  'privateRideMinBookingHours',
  'privateRideRefundRestrictionHours',
  'matchingNoDriverNotifyHours',
  'matchingLastNotifyHours',
  'cancellationFreeWindowHours',
  'cancellationPercentage50Hours',
  'waitingReminderIntervals',
  'waitingTimeMinutes',
  'dayFareInitialCharge',
  'dayFarePerKMRate',
  'dayFareWaitingCharge',
  'nightFareInitialCharge',
  'nightFarePerKMRate',
  'nightFareWaitingCharge',
  'holidayIncreasePercentage',
  'perLuggageCharge',
  'fivePassengerExtraChargePercentage',
  'sixPassengerExtraChargePercentage',
  'baseFare',
  'splitRideMatchedSurchargePercent',
  'platformVat',
  'platformCommissionPercent',
  'driverPlatformFeePercent',
  'driverVatPercent',
  'supportContract',
  'supportEmail',
] as const;

export const ALLOWED_KEYS = [
  ...GENERAL_KEYS,
  'userTramsAndCondition',
  'providerTramsAndCondition',
] as const;

