FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache tzdata dumb-init && \
    ln -sf /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && \
    echo "Asia/Dhaka" > /etc/timezone

COPY package*.json ./
COPY tsconfig.json ./
COPY nodemon.json ./
COPY src ./src

RUN npm install

ENV NODE_ENV=development
ENV TZ=Asia/Dhaka
ENV TIME_ZONE=Asia/Dhaka

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "dev"]
