FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache tzdata dumb-init && \
    ln -sf /usr/share/zoneinfo/Asia/Nicosia /etc/localtime && \
    echo "Asia/Nicosia" > /etc/timezone

COPY package*.json ./
COPY tsconfig.json ./
COPY nodemon.json ./
COPY src ./src

RUN npm install

ENV NODE_ENV=development
ENV TZ=Asia/Nicosia
ENV TIME_ZONE=Asia/Nicosia

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "dev"]
